### ISSUE TITLE
Upcoming Events Slider on Homepage

### ISSUE THREAD

**Issue by theseanodell** [tetratelabs/getistio.io#41]
Can we limit the number of events that are displayed on the Upcoming events slider?

It is currently offset when 4 events are available.

![Screen Shot 2021-01-29 at 11 56 04 AM](https://user-images.githubusercontent.com/9096060/106310699-90f3a580-6229-11eb-84d2-b564202606d9.png)

**Comment by lunchboxav** [comment]
Yes @theseanodell I will create a slider for this occurence. Thank you for the feedback.

**Comment by lunchboxav** [comment]
So the plan is to have 6 events at once, and a slider will appear to help to look at those 6.
