### ISSUE TITLE
Update design/content on /download

### ISSUE THREAD

**Issue by oletizi** [tetratelabs/getistio.io#62]
From Feb 2, 2021 conversation with Prasad:

- Make download and install of getistio the primary CTA
- Links to platform-specific distro pages should be available, but not highlighted
- Administrivia about what versions are available and EOL announcements can also be pushed down to distro matrix pages

**Comment by PetrMc** [comment]
@oletizi / @deva26 - just pushed new Download pages that render the manifest and return only the most recent version - please let me know if it's what needed. Thank you!
