### ISSUE TITLE
Integrate Venafi partner content

### ISSUE THREAD

**Issue by oletizi** [tetratelabs/getistio.io#74]
Description: Engineering and security teams are making Istio the standard for connecting Kubernetes applications with service mesh. Running Istio in production means trusted machine identities – digital certificates – must be used. Venafi makes it easy for developers to access trusted, enterprise-approved machine identities. Security teams get complete visibility and confidence that policy is automatically enforced. Venafi supports Istio with industry standard cert-manager created by Jetstack. GetIstio with Venafin and Jetstack provides an easy way for users to get started with Istio and cert-manager and maintain deployment.
 
Links:
cert-manager – https://marketplace.venafi.com/details/jetstack-cert-manager/
cert-manager + Istio for Gateway – https://istio.io/latest/docs/ops/integrations/certmanager/ [istio.io]
cert-manager + Istio for mTLS – https://github.com/cert-manager/istio-csr [github.com]
Venafi - https://www.venafi.com

**Comment by lunchboxav** [comment]
Orion, does Venafi has specific tutorial/technical docs that they want to or require us to write in GetIstio docs?

**Comment by lunchboxav** [comment]
Or can I include the write up here https://istio.io/latest/docs/ops/integrations/certmanager/ on our partner documentation page? @oletizi ?

**Comment by lunchboxav** [comment]
Fixes for this is covered in PR  #94

**Comment by lunchboxav** [comment]
closed via #94
