### ISSUE TITLE
Multilanguage is not working

### ISSUE THREAD

**Issue by lunchboxav** [tetratelabs/getistio.io#76]
Multilanguage seems pretty buggy now. I can change from En - Zh, but after being in Zh, back to En is not working. Will look into this.

**Comment by lunchboxav** [comment]
@rootsongjc if you have experience the same, pls let me know

**Comment by rootsongjc** [comment]
@lunchboxav As far as I see, only the pages in this box are not working. Do you have other pages that have the problem?

![image](https://user-images.githubusercontent.com/3328185/107015667-f8849480-67d7-11eb-85f8-900dd2b1631a.png)

**Comment by lunchboxav** [comment]
I think this is the thing that @PetrMc mentioned yesterday. Essentially, when we change language, the html header changes, but when we visit reference, there's a redirection happens which I think mismatches the whole html header thing, thus making the content somewhat in limbo. I will look into this more.

**Comment by lunchboxav** [comment]
yes @rootsongjc It happens only on that section, other section seems to be working well.

**Comment by lunchboxav** [comment]
hmm, I discovered something interesting. even when I'm in English mode, if I click Reference, it'll use Chinese directly. I have no idea what caused, but I'll keep on looking.

cc: @rootsongjc

**Comment by lunchboxav** [comment]
I think I know what causes that aforementioned behaviour. So, if you run `hugo` in your local machine, to build the getistio website, you'll notice that the `getistio-cli/reference` directory is built to HTML files with the header that goes like this:

```
<!DOCTYPE html>
<html lang="zh-cn"><head>
  <meta charset="utf-8">
  <title>getistio check-upgrade</title>
  ...
```

So no wonder, even when I'm in English, whenever I go into that directory, I always got Chinese content. I'm looking into a way to solve this, but I think you guys should know @rootsongjc @PetrMc

**Comment by rootsongjc** [comment]
I think the URL of the reference section is not rendered correctly, and I can see from the URL that `zh` is not added.

**Comment by lunchboxav** [comment]
yes, and that one too. I haven't founded what causes this, so, bare with me, I think this is going to be quiet long.

**Comment by PetrMc** [comment]
to add here - it's what I'm seeing - can reproduce any time. (please see the attachment)

![2021-02-05_16-20-21](https://user-images.githubusercontent.com/19846180/107103102-4f3aa000-67d1-11eb-98c2-18471dbb1a2f.gif)

**Comment by lunchboxav** [comment]
yeah, can confirm that bug. If you try running `hugo` to build, this error persists. Seems like even though we put content in `zh` and `en` folders, some of the files in `en` folders are translated to chinese. Take a look at my comment above and notice this line

```
<html lang="zh-cn"><head>
```

This multilanguage thing is pretty broken it seems. And I can't understand the cause. It seems like worst case scenario, we have to leave this feature and come back after launch.

**Comment by lunchboxav** [comment]
Aha, founded the solution. Fix is here :D
